# Generated by Django 4.0.4 on 2022-06-13 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='nuevoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreUsuario', models.CharField(max_length=50)),
                ('psw', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('edad', models.IntegerField()),
                ('genero', models.CharField(max_length=1)),
            ],
        ),
    ]
